#!/bin/sh

set -e
ln -s /home/sqale/etc/database.yml /home/sqale/current/config/database.yml
ln -s /home/sqale/etc/.env /home/sqale/current/.env
cd /home/sqale/current
bundle exec rake assets:precompile
bundle exec whenever --update-crontab